apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j3hv0whyh-python 
  janus-idp.io/tekton: j3hv0whyh-python
  backstage.io/kubernetes-id: j3hv0whyh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j3hv0whyh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml